namespace Enums
{
	public enum CS
	{
		FireRate,
		BulletsPerShot,
		Spread,
		Damage,
		Health,
		Armor,

		DOT,
		Duration,
		Radius,
		SplashDamage,
		Bonus,
		Heal,
		PoisonDamage,
		AttackSpeedPenalty,
		DamageBonus,
		Interval,
		BlessingMinHealAmount,
		BlessingLevelIncreaseAmount,
		EnrageMinDamage,
		EnrageLevelUpAmount,
		ExecuteDamagePerMissingHP,
		DivineShieldHP,
		DivineShieldDuration,
		RedirectionDamageMultiplier,
		HellfireDamage,
		BloodlustCritDamageMultiplier,
		BloodlustCritChance,
		BloodlustLevelsOnCrit,
		CritChance,
		CritDamage,
		RagePotionAtkSpeedBonus,
		RagePotionDamagePenalty,
		RagePotionBonusDuration,
		RagePotionPenaltyDuration
	}
}